Option Compare Database   'Use database order for string comparisons

Sub Initialize_AutoCAD(TheScale, M, n, dx, dy, h, W)

On Error Resume Next
'On Error GoTo 0
dx = W: dy = h  'Report drawing size 7.82 x 10.12 for 8.5 x 11
M = 12: n = 0.375 'scale default
'Dim aCAD As Object
'Dim aCAD As CAD.Object
'Set aCAD = GetObject(ScriptPath & "model.dwg")
'Set AutoCAD = aCAD.GetInterfaceObject("AutoCAD.Application")
'Set aCADDocument = AutoCAD.Application.ActiveDocument
g_TextStyle = LocalVariable("Form_DrawingSetup_Font")
'Dim ACADApplication As AutoCAD.IAcadApplication
'Set ACADsPViewPort = ACADsDocument.ActivePViewport
'Call aCADDocument.SetVariable("SnapMode", 0)
Print #1, "Snap Off"
g_Thickness = 0
'Call aCADDocument.SetVariable("Thickness", 0)
Print #1, "Thickness 0"
g_Elevation = 0
'Call aCADDocument.SetVariable("Elevation", 0)
Print #1, "Elevation 0"
Print #1, "DVIEW  OFF X"
'Call aCADDocument.SetVariable("TileMode", 0)
Print #1, "Tilemode 0 MSpace" 'If ThePartsType = 2 And LocalSettings!DrawTitle Then Print #1, "Tilemode 0 MSpace" Else Print #1, "Tilemode 1"
Print #1, "UCS World"
'Call aCADDocument.SetVariable("UCSIcon", 0)
Print #1, "UCSIcon All OFF"
'Call aCADDocument.SetVariable("TextQLTY", 0)
'Call aCADDocument.SetVariable("TextFill", 1)
'Call aCADDocument.SetVariable("FillMODE", 0)
Print #1, "TextQlty 0 TextFill 1 Fill off"
'Call aCADDocument.SetVariable("DIMFIT", 4)
Print #1, "DIMFIT 4" 'leader
'Call aCADDocument.SetVariable("DIMEXE", 1)
Print #1, "DIMEXE 1" 'line extension
'Call aCADDocument.SetVariable("DIMEXO", 0)
'Call aCADDocument.SetVariable("DIMBLK1", ".")
'Call aCADDocument.SetVariable("DIMBLK2", ".")
'Call aCADDocument.SetVariable("DIMASZ", 0)
Print #1, "DIMEXO 0 DIMBLK1 . DIMBLK2 . DIMASZ 0" 'arrows/line extensions
'Call aCADDocument.SetVariable("DIMTXT", g_TextSize)
Print #1, "DIMTXT " & g_TextSize
'Call aCADDocument.SetVariable("DIMJUST", 0)
Print #1, "DIMJUST 0" 'center text
'Call aCADDocument.SetVariable("DIMTAD", 1)
Print #1, "DIMTAD 1" 'horizontal text below line
'Call aCADDocument.SetVariable("DIMTIH", 0)
Print #1, "DIMTIH Off" 'text along line
'Call aCADDocument.SetVariable("DIMTOFL", 1)
Print #1, "DIMTOFL On" 'force dim inside line
'Call aCADDocument.SetVariable("DIMZIN", 12)
Print #1, "DIMZIN 12" 'supress zeros
'Call aCADDocument.SetVariable("DIMTXSTY", LocalVariable("Form_DrawingSetup_Font"))
Print #1, "DIMTXSTY " & LocalVariable("Form_DrawingSetup_Font") 'LocalSettings!LocalSettingText4 'dim text style
'Call aCADDocument.SetVariable("DIMTXT", g_DimSize)
Print #1, "DIMTXT " & g_DimSize '
'Call aCADDocument.SetVariable("PDMODE", 0)
'Call aCADDocument.SetVariable("PDSIZE", 0)
'Call aCADDocument.SetVariable("BLIPMODE", 0)
Print #1, "PDMODE 0 PDSIZE 0 BLIPMODE OFF"
'Call aCADDocument.SetVariable("FILEDIA", 1)
Print #1, "FILEDIA 1"
If InStr(TheScale, "12in.") Then M = 12: n = 12
If InStr(TheScale, "6in.") Then M = 12: n = 6
If InStr(TheScale, "3in.") Then M = 12: n = 3
If InStr(TheScale, "1in.") Then M = 12: n = 1
If InStr(TheScale, ".75in.") Then M = 12: n = 0.75
If InStr(TheScale, ".5in.") Then M = 12: n = 0.5
If InStr(TheScale, "1.5in.") Then M = 12: n = 1.5
If InStr(TheScale, ".375in.") Then M = 12: n = 0.375
If InStr(TheScale, ".25in.") Then M = 12: n = 0.25
g_AutoCADInit = True

End Sub